name: Upload Package to PyPI

on:
  push:
    branches:
    - master
    - releases/*
    - features/*

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade setuptools twine
    
    - name: Build package
      working-directory: library
      run: |
        python3 setup.py bdist_wheel
        python3 setup.py sdist

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: library/