name: Upload Package to PyPI

on:
  push:
    branches:
    - master
    - releases/*
    - features/*

jobs:
  upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade setuptools tox twine
    - name: Run Tests
        working-directory: library
        run: |
          tox -e py
    - name: Build package
        working-directory: library
        run: |
          python3 setup.py bdist_wheel
        	python3 setup.py sdist

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: library/